spring:
  application:
    name: Student-Management-System
  datasource:
    url:  jdbc:mysql://localhost:3306/practice
    username: root
    password: Kunal@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port:  9090